
version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2015

# test: off

install: 
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - msbuild RefactoringEssentials.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery